version: '1'

test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.12
  script: |
    #!/usr/bin/env bash
    echo "Do nothing yet"

static-scan:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.12
  script: |
    #!/bin/bash
    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
     trap env EXIT
     env
     set -x
    fi
    pwd

    if which tfsec > /dev/null 2>&1; then
      tfsec --version
    else 
      echo "Installing tfsec"
      curl -sL https://github.com/aquasecurity/tfsec/releases/download/v0.58.6/tfsec-linux-amd64 -o /usr/bin/tfsec && chmod +x /usr/bin/tfsec
      tfsec --version
    fi

    TF_STATIC_SCAN_STATUS="${WORKSPACE}/tf-static-scan-status"
    touch "${TF_STATIC_SCAN_STATUS}"

    mkdir -p "${WORKSPACE}/__tfsec_scan__"
    TFSEC_DIR="${WORKSPACE}/__tfsec_scan__"

    list_repos | while IFS= read -r repo ; do
      url="$(load_repo "$repo" url)"
      sha="$(load_repo "$repo" commit)"
      branch="$(load_repo "$repo" branch)"
      path="$(load_repo "$repo" path)"

      echo "repo=$repo url=$url sha=$sha branch=$branch path=$path"

      tf_vars_file=$(get_env tf_vars_file "")
      if [[ "$tf_vars_file" != "" ]]; then
        export VAR_FILE_ARG=" --tfvars-file ${WORKSPACE}/${path}/$tf_vars_file"
      fi

      echo "tfsec ${WORKSPACE}/${path} $VAR_FILE_ARG"
      tfsec ${WORKSPACE}/${path} $VAR_FILE_ARG --format json > "${TFSEC_DIR}/${repo}_tfsec_out.json"
      tfsec ${WORKSPACE}/${path} $VAR_FILE_ARG 
      exit_code=$?
      if [ $exit_code -ne 0 ]; then
        echo "failure" >> "${TF_STATIC_SCAN_STATUS}"
      fi

      save_result static-scan "${TFSEC_DIR}/${repo}_tfsec_out.json"

    done

    echo "exiting accordingly"
    #
    # check if any of the scans failed
    #
    if [ "$(cat "${TF_STATIC_SCAN_STATUS}")" = "failure" ]; then
        TF_STATIC_SCAN_RESULTS_STATUS="failure"
        exit 1
    else
        TF_STATIC_SCAN_RESULTS_STATUS="success"
    fi

sign-artifact:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/image-signing:1.0.0@sha256:e9d8e354668ba3d40be2aaee08298d2aa7f0e1c8a1829cca4094ec93830e3e6a
  script: |
      #!/usr/bin/env bash
      STAGE_DIND="true"
      STAGE_ABORT_ON_FAILURE="false"
      STAGE_IMAGE_PULL_POLICY="IfNotPresent"
      #source scripts/sign_image.sh
      echo "Nothing to do yet"